version: '3'

services:
  api-gateway:
    build: ./Backend/api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./Backend/api-gateway/src:/usr/src/app/src
      - ./Backend/common-proto:/usr/src/app/node_modules/common-proto
    command: npm run start:dev
    environment:
      - PORT=3000
      - HOST_PRODUCT_SERVICE=product-services
      - PORT_PRODUCT_SERVICE=3001
      - URL_GRPC_AUTH_SERVICE=auth-services:50051
    depends_on:
      - auth-services 
      - product-services  

  auth-services:
    build: ./Backend/auth-services
    ports:
      - "50051:50051"
    volumes:
      - ./Backend/auth-services/src:/usr/src/app/src
      - ./Backend/common-proto:/usr/src/app/node_modules/common-proto
    command: npm run start:dev
    environment:
      - URL_GRPC=0.0.0.0:50051
      - DB_CONNECTION=postgres
      - DB_HOST=db_postgres
      - DB_PORT=5432
      - DB_DATABASE=ikbo
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db_postgres

  # product-services:
  #   build: ./Backend/product-services
  #   ports:
  #     - "50053:50053"
  #   volumes:
  #     - ./Backend/product-services/src:/usr/src/app/src
  #     - ./Backend/common-proto:/usr/src/app/node_modules/common-proto
  #   command: npm run start:dev
  #   environment:
  #     - URL_GRPC=0.0.0.0:50053
  #     - DB_CONNECTION=postgres
  #     - DB_HOST=db_postgres
  #     - DB_PORT=5432
  #     - DB_DATABASE=ikbo
  #     - DB_USERNAME=postgres
  #     - DB_PASSWORD=postgres
  #   depends_on:
  #     - db_postgres

  product-services:
    build: ./Backend/inventory-services
    ports:
      - "3001:3001"
    volumes:
      - ./Backend/inventory-services/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - DB_CONNECTION=postgres
      - DB_HOST=db_postgres
      - DB_PORT=5432
      - DB_DATABASE=ikbo
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db_postgres

  db_postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ikbo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend-app:
    build: ./Frontend/ikbo
    ports:
      - "80:80"
    volumes:
      - ./Frontend/ikbo/src:/usr/src/app/src
    # command: npm start
    environment:
      - VITE_APP_VERSION=v1.0.0
      - GENERATE_SOURCEMAP=false
      - VITE_PORT=3002
      - PUBLIC_URL=localhost
      - VITE_APP_BASE_NAME=/
      - VITE_API_URL=api-gateway:3000
    depends_on:
      - api-gateway
      - auth-services 
      - product-services  