// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.28.2
// source: common.proto

/* eslint-disable */

export const protobufPackage = "common";

export interface PaginateRequest {
  page: number;
  limit: number;
}

export interface PaginationObject {
  page: number;
  perPage: number;
  from: number;
  to: number;
  total: number;
}

export interface DateMessage {
  year: number;
  month: number;
  day: number;
}

export const COMMON_PACKAGE_NAME = "common";
