# FROM node:21-alpine3.19

# WORKDIR /usr/src/app

# COPY package.json ./
# COPY package-lock.json ./

# RUN npm install

# COPY . .
# EXPOSE 3002


# Usa una imagen base de Node.js para construir la aplicación
FROM node:21-alpine AS build

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia el archivo package.json y package-lock.json
COPY package.json ./
COPY package-lock.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de la aplicación
COPY . .

# Construye la aplicación para producción
RUN npm run build

# Usa una imagen base de Nginx para servir los archivos estáticos
FROM nginx:alpine

# Copia los archivos generados en la etapa de construcción al contenedor Nginx
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 80
EXPOSE 80

# Comando por defecto para ejecutar Nginx
CMD ["nginx", "-g", "daemon off;"]