name: Prod deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Increment version
        run: |
          npm version patch

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # ARGS: "-rltgoDzvO --delete"
          SOURCE: 'dist/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_HOME }}
          REMOTE_USER: ${{ secrets.REMOTE_USER_HOME }}
          TARGET: public_html/ecommerce
          EXCLUDE: '/build/, /node_modules/'

      - name: Push version change
        run: |
          git config --local user.email ${{ secrets.EMAIL_REPOSITORY }}
          git config --local user.name ${{ secrets.USER_REPOSITORY }}
          git add package.json
          git commit -m "ci: increment version"
          git push origin master 